import { test, expect } from '@playwright/test';
import { testRedis } from '../helpers/redis.mjs';
import { passwordHash } from '../../server/admin-auth.mjs';
import { makeAdminHandler } from '../../server/admin-handler.mjs';
import { makeSubmissionHandler } from '../../server/submissions.mjs';
import { makePublicHandler } from '../../server/public-community.mjs';
test.describe.configure({mode:'serial'});
test.skip(!process.env.DIGIVATED_TEST_REDIS_PORT,'Requires the isolated local Redis test fixture.');
const base='http://127.0.0.1:4321';
const password='Browser fixture owner password!';
for(const width of [375,768,1440])test(`owner lifecycle with real Redis and protected packet at ${width}px`,async({page})=>{
 test.setTimeout(90000);
 const redis=testRedis(13);await redis(['FLUSHDB']);
 const env={NODE_ENV:'test',DIGIVATED_ADMIN_ORIGIN:base,SUBMISSIONS_ORIGIN:base,DIGIVATED_ADMIN_PASSWORD_HASH:await passwordHash(password),DIGIVATED_ADMIN_SESSION_SECRET:'a'.repeat(64)};
 const handlers={'/api/admin':makeAdminHandler({redis,env}),'/api/submissions':makeSubmissionHandler({redis,env}),'/api/projects':makePublicHandler('projects',{redis}),'/api/content':makePublicHandler('content',{redis})};
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**',async route=>{
  const url=new URL(route.request().url());const handler=handlers[url.pathname];
  if(!handler)return route.fulfill({status:401,contentType:'application/json',body:'{"code":"invalid_access"}'});
  const req={url:url.pathname+url.search,method:route.request().method(),body:route.request().postData()||undefined,headers:await route.request().allHeaders()};
  let status=200,body:any;const headers:Record<string,string>={};const res={set statusCode(value:number){status=value;},setHeader:(key:string,value:string)=>headers[key]=value,end:(value:any)=>body=value};
  await handler(req,res);await route.fulfill({status,headers,body});
 });
 await page.setViewportSize({width,height:900});
 await page.goto(base+'/submit-project');
 await page.getByLabel('Creator Name').fill('Private reviewer fixture');await page.getByLabel('Email',{exact:false}).fill('private@example.com');await page.getByLabel('Project Name',{exact:true}).fill('Reviewable fixture');await page.getByLabel('Project URL').fill('https://example.com');await page.getByLabel('Project Description').fill('A real-handler test fixture that must never be deployed.');await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('Apps');await page.getByRole('checkbox').check();await page.getByRole('button',{name:/Submit Your Project/}).click();await expect(page.locator('#submission-status')).toContainText('received for review');
 await page.goto(base+'/discover');await expect(page.locator('[data-project]')).toHaveCount(0);
 await page.goto(base+'/admin');await expect(page.getByRole('heading',{name:'Welcome back.'})).toBeVisible();
 const unauth=await page.evaluate(async()=>{const response=await fetch('/api/admin?action=list&kind=submission');return {status:response.status,body:await response.text()};});expect(unauth.status).toBe(401);expect(unauth.body).not.toContain('private@example.com');
 await page.getByLabel('Owner password').fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.locator('#owner-dashboard')).toBeVisible();await expect(page.getByRole('button',{name:'Review project',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.cookie)).not.toContain('digivated-admin');expect(await page.evaluate(()=>localStorage.length)).toBe(0);
 await page.screenshot({path:test.info().outputPath(`dashboard-${width}.png`),fullPage:true});
 await page.getByRole('button',{name:'Review project',exact:true}).click();await expect(page.locator('#owner-private-details')).toContainText('private@example.com');await expect(page.getByRole('button',{name:'Make Featured Build'})).toBeDisabled();
 await page.screenshot({path:test.info().outputPath(`review-${width}.png`),fullPage:true});
 await page.getByRole('button',{name:'Approve & publish'}).click();await expect(page.locator('#owner-editor-status')).toContainText('now public');await page.getByLabel('Digivated Pick',{exact:true}).check();await page.getByRole('button',{name:'Make Featured Build'}).click();await expect(page.locator('#owner-editor-status')).toContainText('now public');
 await page.getByRole('button',{name:'Close',exact:true}).click();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.goto(base);await expect(page.locator('[data-live-projects="featured"]')).toContainText('Reviewable fixture');await expect(page.locator('[data-live-projects="picks"]')).toContainText('Reviewable fixture');expect(await page.locator('body').innerText()).not.toContain('private@example.com');
 await page.goto(base+'/admin');await page.getByRole('button',{name:'Articles',exact:true}).click();await page.getByRole('button',{name:'New article',exact:true}).click();await page.getByLabel('Article URL slug',{exact:false}).fill('fixture-article');await page.getByLabel('Article title',{exact:true}).fill('Fixture article title');await page.getByLabel('Short description',{exact:true}).fill('A fixture resource summary.');await page.getByLabel('Article content',{exact:false}).fill('## A useful heading\n\n<script>window.fixtureXss=true</script>\n\nUseful article text.');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.locator('#owner-editor-status')).toContainText('not public');
 const draft=await page.evaluate(async()=>{const response=await fetch('/api/content?type=resource&id=fixture-article');return response.status;});expect(draft).toBe(404);
 await page.getByRole('button',{name:'Publish',exact:true}).click();await expect(page.locator('#owner-editor-status')).toContainText('now public');await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.goto(base+'/resources');await page.getByRole('link',{name:'Fixture article title',exact:true}).click();await expect(page.getByRole('heading',{name:'Fixture article title',exact:true})).toBeVisible();await expect(page.locator('#article-body')).toContainText('<script>window.fixtureXss=true</script>');expect(await page.evaluate(()=>window['fixtureXss'])).toBeUndefined();
 await page.goto(base+'/admin');await page.getByRole('button',{name:'Products',exact:true}).click();await expect(page.locator('#owner-protected')).toContainText('UI/UX Prompt Packet');await page.getByRole('button',{name:'New product',exact:true}).click();await page.getByLabel('Product identifier',{exact:false}).fill('fixture-product');await page.getByLabel('Product name',{exact:true}).fill('Fixture product');await page.getByLabel('Short description',{exact:true}).fill('A fixture product description.');await page.getByLabel('Existing product page URL',{exact:false}).fill('https://example.com/product');await page.getByRole('button',{name:'Publish',exact:true}).click();await expect(page.locator('#owner-editor-status')).toContainText('now public');await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.goto(base+'/products');await expect(page.getByRole('heading',{name:'Fixture product',exact:true})).toBeVisible();await page.getByRole('link',{name:'View UI/UX Prompt Packet',exact:true}).click();await expect(page.locator('.purchase-link')).toHaveAttribute('href','https://mccovery.gumroad.com/l/ui-prompt-package');await page.locator('.purchase-link').click({trial:true});
 await page.goto(base+'/admin');await page.getByRole('button',{name:'Review project',exact:true}).click();await page.getByRole('button',{name:'Archive',exact:true}).click();await expect(page.locator('#owner-editor-status')).toContainText('not public');await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.getByRole('heading',{name:'Welcome back.'})).toBeVisible();
 await page.goto(base+'/discover');await expect(page.locator('[data-project]')).toHaveCount(0);expect(errors).toEqual([]);await redis(['FLUSHDB']);
});
