import demo from '../data/demo.json';
import catalog from '../data/catalog.json';
const $=(id)=>document.getElementById(id);
const escape=(value)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='uip-toolkit-v1', KEY='uip-edition-key-v1';
const empty=()=>({version:1,favorites:[],completed:[],checks:[],steps:[],notes:'',brief:{}});
let state=empty(),edition=demo,unlocked=false,toastTimer;
function toast(text){$('toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',4500);}
const unique=(a)=>[...new Set(a)];
function validate(data){
 if(!data||data.version!==1)throw Error('This is not a supported UI Prompt Package backup.');
 const nums=(x)=>Array.isArray(x)&&x.length<=75&&x.every(n=>Number.isInteger(n)&&n>=1&&n<=75);
 const strings=(x,pattern)=>Array.isArray(x)&&x.length<=200&&x.every(n=>typeof n==='string'&&pattern.test(n));
 if(!nums(data.favorites)||!nums(data.completed)||!strings(data.checks,/^[1-8]-[0-9]{1,2}$/)||!strings(data.steps,/^[1-8]-[1-9][0-9]?$/)||typeof data.notes!=='string'||data.notes.length>20000)throw Error('The backup has invalid or oversized data.');
 const brief={};for(const name of ['template','app','screen','audience','goal','issue','constraints','mode']){const v=data.brief?.[name];if(v!==undefined){if(typeof v!=='string'||v.length>2000)throw Error('The saved brief is invalid.');brief[name]=v;}}
 return {version:1,favorites:unique(data.favorites),completed:unique(data.completed),checks:unique(data.checks),steps:unique(data.steps),notes:data.notes,brief};
}
try{const raw=localStorage.getItem(STORE);if(raw)state=validate(JSON.parse(raw));}catch{toast('Saved data could not be loaded. Import a backup if you have one.');}
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));return true;}catch{toast('Browser storage is unavailable or full. Export a backup to keep your work.');return false;}}
function toggle(list,value){state[list]=state[list].includes(value)?state[list].filter(v=>v!==value):[...state[list],value];save();}
function available(id){return edition.prompts.find(p=>p.id===id);}
async function decrypt(key){
 if(!/^[a-f0-9]{64}$/i.test(key))throw Error('Check the access key and try again.');
 const response=await fetch('/edition.enc.json');if(!response.ok)throw Error('The edition could not load. Check your connection and try again.');
 const bundle=await response.json();const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
 try{const cryptoKey=await crypto.subtle.importKey('raw',Uint8Array.from(key.match(/../g),h=>parseInt(h,16)),{name:'AES-GCM'},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(bundle.iv)},cryptoKey,bytes(bundle.data));const parsed=JSON.parse(new TextDecoder().decode(plain));if(parsed.version!==1||parsed.prompts.length!==75)throw Error();return parsed;}catch{throw Error('That key did not unlock this edition. Check it and try again.');}
}
try{const key=sessionStorage.getItem(KEY);if(key){edition=await decrypt(key);unlocked=true;}}catch{toast('The full edition could not reopen. Enter your key again or check your connection.');}
if(unlocked){$('edition-label').textContent='Full edition unlocked';if($('lock-edition')){$('lock-edition').hidden=false;$('unlock-status').textContent='The complete edition is unlocked in this tab.';}}
function row(p){const free=available(p.id);return `<article class="prompt-row"><span class="prompt-id">${String(p.id).padStart(2,'0')}</span><div><span class="tiny">${escape(p.category)}</span><h3>${escape(p.title)}</h3><p>${escape(p.summary)}</p></div><div class="row-actions"><span class="pill ${free?'':'locked'}">${free?(unlocked?'Available':'Free sample'):'Full edition'}</span><button class="button small" data-open="${p.id}">${free?'Read prompt':'Preview topic'}</button><button class="button small" data-favorite="${p.id}" aria-label="${state.favorites.includes(p.id)?'Unsave':'Save'} ${escape(p.title)}" aria-pressed="${state.favorites.includes(p.id)}">${state.favorites.includes(p.id)?'Saved':'Save'}</button></div></article>`;}
function renderLibrary(){if(!$('prompt-list'))return;const q=$('search').value.trim().toLowerCase(),cat=$('category').value,filter=$('availability').value;const rows=catalog.prompts.filter(p=>(!q||`${p.title} ${p.summary} ${p.category}`.toLowerCase().includes(q))&&(!cat||p.category===cat)&&(filter!=='available'||available(p.id))&&(filter!=='favorites'||state.favorites.includes(p.id)));$('prompt-list').innerHTML=rows.map(row).join('')||'<div class="empty"><h2>No matching prompts.</h2><p>Try a broader word or choose All topics.</p><button class="button" id="reset-filters">Clear filters</button></div>';$('results-count').textContent=`${rows.length} ${rows.length===1?'prompt':'prompts'} · ${edition.prompts.length} available in your edition`;$('reset-filters')?.addEventListener('click',()=>{$('search').value='';$('category').value='';$('availability').value='all';renderLibrary();});}
if($('category')){[...new Set(catalog.prompts.map(p=>p.category))].forEach(c=>$('category').add(new Option(c,c)));if(new URLSearchParams(location.search).has('sample'))$('availability').value='available';['search','category','availability'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderLibrary));renderLibrary();}
const dialog=$('prompt-dialog');
function openPrompt(id){const meta=catalog.prompts.find(p=>p.id===id);if(!meta||!dialog)return;const p=available(id);$('dialog-category').textContent=`${String(id).padStart(2,'0')} · ${meta.category}`;
$('dialog-content').innerHTML=`<h2 id="dialog-title">${escape(meta.title)}</h2><p>${escape(meta.summary)}</p>`+(p?`<div class="actions"><button class="button primary" data-copy="${id}">Copy prompt</button><a class="button" href="/builder?prompt=${id}">Adapt to my project</a><button class="button" data-complete="${id}" aria-pressed="${state.completed.includes(id)}">${state.completed.includes(id)?'Reviewed':'Mark reviewed'}</button></div><h3>When to use it</h3><div class="reading">${escape(p.when)}</div><h3>What to give the AI</h3><div class="reading">${escape(p.context)}</div><h3>Copy & paste prompt</h3><div class="prompt-text">${escape(p.prompt)}</div><h3>A good result should</h3><div class="reading">${escape(p.result)}</div>${p.watchout?`<h3>Watch out</h3><p>${escape(p.watchout)}</p>`:''}<h3>Useful follow-ups</h3><div class="reading">${escape(p.followups)}</div>`:`<div class="panel"><span class="pill locked">Full edition</span><h3>This topic is included in the complete playbook.</h3><p>The full prompt, context, and review guidance are protected. Checkout is not open yet.</p><a class="button primary" href="/access">Edition access</a><a class="button" href="/library?sample=1">Try the free samples</a></div>`);if(!dialog.open)dialog.showModal();}
$('close-dialog')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>{if(location.hash.startsWith('#prompt-'))history.replaceState(null,'',location.pathname+location.search);});
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Prompt copied.');}catch{toast('Clipboard access is unavailable. Select the prompt text and copy it manually.');}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open)openPrompt(Number(b.dataset.open));if(b.dataset.favorite){toggle('favorites',Number(b.dataset.favorite));renderLibrary();renderToolkit();if(b.isConnected){b.setAttribute('aria-pressed',String(state.favorites.includes(Number(b.dataset.favorite))));b.textContent=state.favorites.includes(Number(b.dataset.favorite))?'Saved':'Save';}}if(b.dataset.copy){const p=available(Number(b.dataset.copy));if(p)copy(p.prompt);}if(b.dataset.complete){toggle('completed',Number(b.dataset.complete));b.setAttribute('aria-pressed',String(state.completed.includes(Number(b.dataset.complete))));b.textContent=state.completed.includes(Number(b.dataset.complete))?'Reviewed':'Mark reviewed';}});
const hashPrompt=()=>{const match=location.hash.match(/^#prompt-(\d+)$/);if(match)openPrompt(Number(match[1]));};hashPrompt();window.addEventListener('hashchange',hashPrompt);
function locked(title){return `<section class="panel"><span class="pill locked">Full edition</span><h2>${escape(title)}</h2><p>Included in the complete playbook.</p><a class="button" href="/access">Edition access</a></section>`;}
function workflow(w){const done=w.steps.filter(id=>state.steps.includes(`${w.id}-${id}`)).length;return `<section class="panel"><div class="workflow-meta"><h2>${escape(w.title)}</h2><span class="quiet">${done}/${w.steps.length} steps</span></div><progress max="${w.steps.length}" value="${done}" aria-label="${escape(w.title)} progress"></progress>${w.steps.map(id=>`<label class="check-item"><input type="checkbox" data-step="${w.id}-${id}" ${state.steps.includes(`${w.id}-${id}`)?'checked':''}/><span>${escape(catalog.prompts.find(p=>p.id===id).title)}</span><a href="/library#prompt-${id}">${available(id)?'Read prompt':'View topic'}</a></label>`).join('')}<p class="quiet" style="margin-top:20px">${escape(w.stop)}</p>${!unlocked?'<p class="quiet">This sample workflow shows the full sequence. Some steps refer to full-edition prompts.</p>':''}</section>`;}
function renderWorkflows(){if($('workflow-list'))$('workflow-list').innerHTML=catalog.workflows.map(meta=>{const w=edition.workflows.find(w=>w.id===meta.id);return w?workflow(w):locked(meta.title);}).join('');}
function renderChecks(){if(!$('checklist-list'))return;let total=0,done=0;$('checklist-list').innerHTML=catalog.checklists.map(meta=>{const c=edition.checklists.find(c=>c.id===meta.id);if(!c)return locked(meta.title);total+=c.items.length;done+=c.items.filter((_,i)=>state.checks.includes(`${c.id}-${i}`)).length;return `<section class="panel"><h2>${escape(c.title)}</h2>${c.items.map((item,i)=>`<label class="check-item"><input type="checkbox" data-check="${c.id}-${i}" ${state.checks.includes(`${c.id}-${i}`)?'checked':''}/><span>${escape(item)}</span></label>`).join('')}</section>`;}).join('');$('check-progress').textContent=`${done} of ${total} available review items checked`;}
renderWorkflows();renderChecks();
document.addEventListener('change',e=>{if(e.target.dataset.check){toggle('checks',e.target.dataset.check);const total=edition.checklists.reduce((n,c)=>n+c.items.length,0);const done=edition.checklists.reduce((n,c)=>n+c.items.filter((_,i)=>state.checks.includes(`${c.id}-${i}`)).length,0);$('check-progress').textContent=`${done} of ${total} available review items checked`;}if(e.target.dataset.step){toggle('steps',e.target.dataset.step);const panel=e.target.closest('.panel');const boxes=[...panel.querySelectorAll('[data-step]')];const done=boxes.filter(b=>b.checked).length;panel.querySelector('progress').value=done;panel.querySelector('.workflow-meta .quiet').textContent=`${done}/${boxes.length} steps`;}});
if($('lesson-list'))$('lesson-list').innerHTML=catalog.lessons.map(meta=>{const l=edition.lessons.find(l=>l.id===meta.id);return l?`<details class="panel"><summary>${escape(l.title)}</summary><div class="lesson-body">${escape(l.body)}</div></details>`:locked(meta.title);}).join('');
const fixes=[['I don’t know what looks wrong',1,'Start with an audit. Fix the top three usability issues before changing the visual style.'],['The phone version feels cramped',2,'Check layout, keyboard behavior, overflow, and touch targets in that order.'],['There are too many buttons and screens',3,'Map the important tasks, then simplify where they live. Preserve useful features.'],['It looks obviously AI-generated',4,'Remove unnecessary decoration and repetitive explanations. Keep the product’s identity.'],['I’m about to launch a feature',5,'Review the real flow, including loading, errors, accessibility, and regression risks.'],['I keep redesigning the same screen',6,'Compare against the original goal and separate usability issues from preferences.'],['I’m adding collaboration',7,'Review invitations, presence, shared activity, and roles before final QA.'],['I’m adding a paid upgrade',8,'Make the offer, costs, access, and billing controls clear before launch.']];
if($('fix-list')){$('fix-list').innerHTML=fixes.map(([title,id,description])=>`<button class="panel fix-choice" data-fix="${id}"><span class="tiny">START HERE · ${String(id).padStart(2,'0')}</span><h3 style="margin-top:16px">${escape(title)}</h3><p>${escape(description)}</p></button>`).join('');$('fix-list').addEventListener('click',e=>{const b=e.target.closest('[data-fix]');if(!b)return;const id=Number(b.dataset.fix),w=edition.workflows.find(w=>w.id===id);$('fix-result').hidden=false;$('fix-result').innerHTML=w?workflow(w):`<h2>${escape(fixes[id-1][0])}</h2><p>${escape(fixes[id-1][2])}</p><p>The complete step-by-step workflow is in the full edition. You can start with the free full UI audit.</p><a class="button primary" href="/library#prompt-1">Open the free audit</a><a class="button" href="/access">Edition access</a>`;$('fix-result').focus();$('fix-result').scrollIntoView({block:'start',behavior:'auto'});});}
function generate(){const form=$('builder-form');if(!form)return;const values=Object.fromEntries(new FormData(form));state.brief=values;save();const p=available(Number(values.template));if(!p)return;let text=p.prompt;const replacements={'[APP NAME]':values.app,'[SCREEN / FEATURE]':values.screen,'[TARGET USER]':values.audience,'[WHAT THE USER SHOULD ACCOMPLISH]':values.goal,"[DESCRIBE IT, OR WRITE 'UNKNOWN']":values.issue||'UNKNOWN'};for(const [from,to] of Object.entries(replacements))text=text.split(from).join(to||from);if(values.mode==='implement')text+='\n\nAfter diagnosing the named issue, implement the smallest targeted fix. Preserve working functionality and user data. List the files changed and tests run. Separate verified results from manual checks still needed.';else text+='\n\nThis is a diagnosis only. Do not edit code yet.';if(values.constraints.trim())text+='\n\nAdditional constraints:\n'+values.constraints.trim();$('built-prompt').value=text;$('copy-built').disabled=false;}
if($('builder-form')){edition.prompts.forEach(p=>$('template').add(new Option(`${String(p.id).padStart(2,'0')} · ${p.title}`,String(p.id))));const form=$('builder-form');for(const [key,value] of Object.entries(state.brief)){const field=form.elements.namedItem(key);if(field&&key!=='template')field.value=value;}const desired=new URLSearchParams(location.search).get('prompt')||state.brief.template;if(desired&&available(Number(desired)))$('template').value=desired;else if(desired)toast('That prompt needs the full edition. The free audit is selected.');form.addEventListener('submit',e=>{e.preventDefault();generate();toast('Your prompt is ready.');});form.addEventListener('input',()=>{state.brief=Object.fromEntries(new FormData(form));save();$('built-prompt').value='';$('copy-built').disabled=true;});$('copy-built').addEventListener('click',()=>copy($('built-prompt').value));}
function renderToolkit(){if(!$('toolkit-stats'))return;$('toolkit-stats').innerHTML=`<div><strong>${state.favorites.length}</strong><span>Saved prompts</span></div><div><strong>${state.completed.length}</strong><span>Prompts reviewed</span></div><div><strong>${state.checks.length}</strong><span>Checklist items reviewed</span></div>`;$('favorites-list').innerHTML=catalog.prompts.filter(p=>state.favorites.includes(p.id)).map(row).join('')||'<p class="empty">No saved prompts yet. <a href="/library">Explore the library</a> and save one for your next project.</p>';}
renderToolkit();
if($('notes')){$('notes').value=state.notes;$('notes').addEventListener('input',()=>{state.notes=$('notes').value;$('notes-status').textContent=save()?'Saved on this device.':'Could not save. Export a backup before leaving.';});$('export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='UI-Prompt-Package-Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('backup-status').textContent='Backup download requested.';});$('import').addEventListener('change',async()=>{try{const file=$('import').files[0];if(!file)return;if(file.size>150000)throw Error('Choose a backup smaller than 150 KB.');const incoming=validate(JSON.parse(await file.text()));const notes=incoming.notes&&incoming.notes!==state.notes?[state.notes,incoming.notes].filter(Boolean).join('\n\n— Imported notes —\n\n'):state.notes;if(notes.length>20000)throw Error('The combined notes exceed 20,000 characters. Shorten them before importing.');const merged={...state,notes};for(const k of ['favorites','completed','checks','steps'])merged[k]=unique([...state[k],...incoming[k]]);if(!Object.values(state.brief).some(Boolean))merged.brief=incoming.brief;state=validate(merged);const saved=save();$('notes').value=state.notes;renderToolkit();$('backup-status').textContent=saved?'Backup merged. Existing saved items were kept.':'Backup merged in memory. Export it now because browser storage is unavailable.';}catch(error){$('backup-status').textContent=error.message||'That backup could not be read.';}finally{$('import').value='';}});}
$('unlock-form')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;$('unlock-status').textContent='Opening your edition…';try{const key=$('access-key').value.trim();edition=await decrypt(key);try{sessionStorage.setItem(KEY,key);}catch{throw Error('Your browser blocked session storage. Allow site storage to unlock across pages.');}unlocked=true;$('access-key').value='';$('unlock-status').textContent='Unlocked. Open the prompt library to use all 75 prompts.';$('lock-edition').hidden=false;$('edition-label').textContent='Full edition unlocked';const a=document.createElement('a');a.href='/library';a.textContent='Open the complete library';a.className='button';$('unlock-status').append(document.createElement('br'),a);}catch(error){$('unlock-status').textContent=error.message;}finally{b.disabled=false;}});
$('lock-edition')?.addEventListener('click',()=>{try{sessionStorage.removeItem(KEY);}catch{}edition=demo;unlocked=false;location.reload();});
