import demo from '../data/demo.json';
import catalog from '../data/catalog.json';
const $=(id)=>document.getElementById(id);
const escape=(value)=>String(value??'').replace(/\uf0b7/g,'•').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const topicNames={
'Audit & Diagnosis':'Find what needs fixing','Layout & Hierarchy':'Organize a screen','Navigation & Information Architecture':'Make navigation easier','Mobile & Responsive':'Improve the phone experience','Color & Typography':'Improve colors & text','Components & Design System':'Keep the design consistent','Forms & Authentication':'Improve forms & sign-in','Onboarding':'Welcome new users','States & Feedback':'Explain loading, errors & success','Dashboards & Data':'Present data clearly','Accessibility':'Make it easier for everyone','AI-Look Cleanup & Copy':'Simplify design & wording','Testing & Final Polish':'Check before you launch','Search & Discovery':'Help people find things','Collaboration & Social UI':'Design shared experiences','Monetization & Upgrade UX':'Explain pricing & upgrades','Localization & Content Resilience':'Support different languages & content','Trust, Privacy & Sensitive Actions':'Protect privacy & important actions','Interaction Feedback & Motion':'Use animation & feedback well'};
const topic=c=>topicNames[c]||c;
$('menu-toggle')?.addEventListener('click',()=>{const open=$('menu-toggle').getAttribute('aria-expanded')!=='true';$('menu-toggle').setAttribute('aria-expanded',String(open));$('menu-toggle').textContent=open?'Close menu':'Menu';$('site-navigation').classList.toggle('is-open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('menu-toggle')?.getAttribute('aria-expanded')==='true'){$('menu-toggle').click();$('menu-toggle').focus();}});

const STORE='uip-toolkit-v1';
try { sessionStorage.removeItem('uip-edition-key-v1'); } catch {}
const empty=()=>({version:1,favorites:[],completed:[],checks:[],steps:[],notes:'',brief:{}});
let state=empty(),edition=demo,unlocked=false,toastTimer;
function toast(text){const host=$('prompt-dialog')?.open?$('prompt-dialog'):document.body;host.append($('toast'));$('toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',4500);}
const unique=(a)=>[...new Set(a)];
function validate(data){
 if(!data||data.version!==1)throw Error('This is not a supported UI Prompt Package backup.');
 const nums=(x)=>Array.isArray(x)&&x.length<=75&&x.every(n=>Number.isInteger(n)&&n>=1&&n<=75);
 const strings=(x,pattern)=>Array.isArray(x)&&x.length<=200&&x.every(n=>typeof n==='string'&&pattern.test(n));
 if(!nums(data.favorites)||!nums(data.completed)||!strings(data.checks,/^[1-8]-[0-9]{1,2}$/)||!strings(data.steps,/^[1-8]-[1-9][0-9]?$/)||typeof data.notes!=='string'||data.notes.length>20000)throw Error('The backup has invalid or oversized data.');
 const brief={};for(const name of ['template','app','screen','audience','goal','issue','constraints','mode']){const v=data.brief?.[name];if(v!==undefined){if(typeof v!=='string'||v.length>2000)throw Error('The saved brief is invalid.');brief[name]=v;}}
 return {version:1,favorites:unique(data.favorites),completed:unique(data.completed),checks:unique(data.checks),steps:unique(data.steps),notes:data.notes,brief};
}
try{const raw=localStorage.getItem(STORE);if(raw)state=validate(JSON.parse(raw));}catch{toast('Saved data could not be loaded. Import a backup if you have one.');}
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));return true;}catch{toast('Browser storage is unavailable or full. Export a backup to keep your work.');return false;}}
function toggle(list,value){state[list]=state[list].includes(value)?state[list].filter(v=>v!==value):[...state[list],value];save();}
function available(id){return edition.prompts.find(p=>p.id===id);}
async function accessRequest(path, options={}) {
 const response=await fetch(path,{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(12000),...options});
 let data;try{data=await response.json();}catch{throw Error('Access is temporarily unavailable. Please try again shortly.');}
 if(!response.ok){const error=Error(data.error||'Please try again shortly.');error.status=response.status;throw error;}
 return data;
}
const protectedScreens=['library','fixes','builder','workflows','checklists','learn','access'];
if(protectedScreens.includes(document.body.dataset.section)) {
 try{edition=await accessRequest('/api/edition');unlocked=true;}
 catch(error){if(error.status!==401){const message='Full-edition access could not be checked. Free samples are still available. Please try again shortly.';if($('unlock-status'))$('unlock-status').textContent=message;else toast(message);}}
}
if(unlocked){$('edition-label').textContent='Full edition unlocked';if($('lock-edition')){$('lock-edition').hidden=false;$('unlock-status').textContent='You’re signed in on this browser. Open the library to continue.';}}
// Recheck after returning from the back-forward cache. Never store paid content locally.
window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
let accessChannel;try{accessChannel=new BroadcastChannel('uip-access');accessChannel.onmessage=()=>location.reload();}catch{}
function row(p){const free=available(p.id);return `<article class="prompt-row"><span class="prompt-id">PROMPT ${String(p.id).padStart(2,'0')}</span><div><span class="tiny">${escape(topic(p.category))}</span><h3>${escape(p.title)}</h3><p>${escape(p.summary)}</p></div><div class="row-actions"><span class="pill ${free?'':'locked'}">${free?(unlocked?'Available':'Free sample'):'Full edition'}</span><button class="button small" data-open="${p.id}">${free?'Read prompt':'Preview topic'}</button><button class="button small" data-favorite="${p.id}" aria-label="${state.favorites.includes(p.id)?'Unsave':'Save'} ${escape(p.title)}" aria-pressed="${state.favorites.includes(p.id)}">${state.favorites.includes(p.id)?'Saved':'Save'}</button></div></article>`;}
function renderLibrary(){if(!$('prompt-list'))return;const q=$('search').value.trim().toLowerCase(),cat=$('category').value,filter=$('availability').value;const rows=catalog.prompts.filter(p=>(!q||`${p.title} ${p.summary} ${p.category} ${topic(p.category)}`.toLowerCase().includes(q))&&(!cat||p.category===cat)&&(filter!=='available'||available(p.id))&&(filter!=='favorites'||state.favorites.includes(p.id)));$('prompt-list').innerHTML=rows.map(row).join('')||'<div class="empty"><h2>No matching prompts.</h2><p>Try a broader word or choose All topics.</p><button class="button" id="reset-filters">Clear filters</button></div>';$('results-count').textContent=`${rows.length} ${rows.length===1?'prompt':'prompts'}${cat?' · '+topic(cat):' · All topics'}${q?' · Search: '+q:''} · ${filter==='available'?'Available to me':filter==='favorites'?'My favorites':'All editions'}`;const params=new URLSearchParams();if(q)params.set('q',$('search').value);if(cat)params.set('topic',cat);if(filter!=='all')params.set('show',filter);history.replaceState(null,'',location.pathname+(params.size?'?'+params.toString():'')+location.hash);$('reset-filters')?.addEventListener('click',()=>{$('search').value='';$('category').value='';$('availability').value='all';renderLibrary();});}
if($('category')){[...new Set(catalog.prompts.map(p=>p.category))].forEach(c=>$('category').add(new Option(topic(c),c)));const query=new URLSearchParams(location.search);$('search').value=query.get('q')||'';if([...$('category').options].some(o=>o.value===query.get('topic')))$('category').value=query.get('topic');if(['all','available','favorites'].includes(query.get('show')))$('availability').value=query.get('show');if(query.has('sample'))$('availability').value='available';['search','category','availability'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderLibrary));renderLibrary();}
$('clear-filters')?.addEventListener('click',()=>{$('search').value='';$('category').value='';$('availability').value='all';history.replaceState(null,'',location.pathname);renderLibrary();$('search').focus();});
const dialog=$('prompt-dialog');
const placeholders=[['[APP NAME]','Your app or project name','Study Planner'],['[SCREEN / FEATURE]','The part you want to review','Signup screen'],['[TARGET USER]','The people who will use it','New college students'],['[WHAT THE USER SHOULD ACCOMPLISH]','The task they should finish','Create an account without confusion'],["[DESCRIBE IT, OR WRITE 'UNKNOWN']",'The problem you noticed; UNKNOWN is fine','The main button is hard to find']];
const resultExamples={
'Audit & Diagnosis':'Must fix: the main action is hard to find. Make it more prominent than secondary links, then check that a first-time visitor can complete the task.',
'Layout & Hierarchy':'The summary and secondary details compete for attention. Place the summary first and group the supporting details below it. Check the reading order on a phone.',
'Navigation & Information Architecture':'Two menu items lead to the same task. Give that task one clearly named home and check that existing links still reach it.',
'Mobile & Responsive':'The form extends beyond the phone screen. Stack its fields vertically and check that the keyboard does not cover the submit button.',
'Color & Typography':'The helper text is difficult to read. Increase its contrast against the background and check it at normal and enlarged text sizes.',
'Components & Design System':'Buttons with the same purpose use different heights and colors. Apply one shared style and verify the loading and disabled states.',
'Forms & Authentication':'The error message does not identify the field to fix. Put a specific message next to that field and preserve the other entered information.',
'Onboarding':'The first screen asks for details that are not needed yet. Ask only for what is necessary to begin, then confirm the user can reach their first useful action.',
'States & Feedback':'An empty list looks like a broken page. Explain that there are no items yet and provide the relevant next action.',
'Dashboards & Data':'The chart does not explain its time period. Label the date range and units so a reader can understand what the numbers mean.',
'Accessibility':'The icon button has no accessible name. Give it a descriptive label and confirm that it can be reached and activated with a keyboard.',
'AI-Look Cleanup & Copy':'Several cards repeat the same instructions. Combine those instructions into one short introduction and preserve the controls people need.',
'Testing & Final Polish':'The main flow works, but the error path loses the draft. Keep the entered values and retest after a failed request.',
'Search & Discovery':'The selected filter is not visible after searching. Show the active filter and provide a reset action. Check a search with no matches.',
'Collaboration & Social UI':'Members cannot tell which actions require an owner. Explain the available actions and verify that permissions are enforced.',
'Monetization & Upgrade UX':'The upgrade screen does not show the billing frequency. Put the price and billing period together before the purchase action.',
'Localization & Content Resilience':'A longer translated label is cut off. Allow it to wrap and test long labels without hiding the action.',
'Trust, Privacy & Sensitive Actions':'The delete confirmation does not say what will be removed. Name the item and explain whether the action can be undone.',
'Interaction Feedback & Motion':'The save action gives no feedback. Show confirmation after saving succeeds and keep any motion optional.'};
const exampleFor=p=>resultExamples[p.category]||'Describe a specific issue, suggest a focused change, and explain how to check it.';
function openPrompt(id){const meta=catalog.prompts.find(p=>p.id===id);if(!meta||!dialog)return;const p=available(id);$('dialog-category').textContent=`Prompt ${String(id).padStart(2,'0')} · ${topic(meta.category)}`;
$('dialog-content').innerHTML=`<h2 id="dialog-title" tabindex="-1">${escape(meta.title)}</h2><p class="tiny">What this helps you do</p><p>${escape(meta.summary)}</p>`+(p?`<div class="actions"><a class="button primary" href="/builder?prompt=${id}">Customize this prompt</a><button class="button" data-copy="${id}">Copy template</button><button class="button" data-complete="${id}" aria-pressed="${state.completed.includes(id)}">${state.completed.includes(id)?'Reviewed':'Mark reviewed'}</button></div><p class="quiet">Customize first, or replace the [bracketed text] yourself after copying. UI means the screens and controls people use; UX means how easy the experience feels.</p><h3>When to use it</h3><div class="reading">${escape(p.when)}</div><h3>What you need</h3><div class="reading">${escape(p.context)}</div><h3>The prompt</h3><div class="prompt-text" tabindex="0" aria-label="Prompt template">${escape(p.prompt)}</div><div class="prompt-guide"><details><summary>What to change · five placeholders</summary><div><dl class="placeholder-list">${placeholders.map(([name,meaning,example])=>`<div><dt><code>${escape(name)}</code></dt><dd>${escape(meaning)}. Example: ${escape(example)}.</dd></div>`).join('')}</dl></div></details><details><summary>How to use this prompt</summary><div><ol><li>Select Customize this prompt and fill in your details.</li><li>Select Build my prompt, then Copy prompt.</li><li>Paste into ChatGPT or Claude with a screenshot, or your AI coding tool with your project open.</li><li>Review the suggestions and ask for one focused improvement.</li><li>Check the actual screen on a phone and desktop after any changes.</li></ol><a href="/start">Read the beginner guide</a></div></details><details><summary>Example result & what to look for</summary><div><p class="tiny">Illustrative example—not an AI-generated result</p><p class="example">${escape(exampleFor(p))}</p><h3>A useful result should</h3><div class="reading">${escape(p.result)}</div></div></details><details><summary>How to improve the result</summary><div><div class="reading">${escape(p.followups)}</div>${p.watchout?`<h3>Watch out for</h3><p>${escape(p.watchout)}</p>`:''}<p>Need simpler wording? Ask: “Explain the main issue in everyday language and give me one next step.”</p></div></details></div><div class="actions"><a class="button primary" href="/builder?prompt=${id}">Customize this prompt</a><button class="button" data-close-prompt>Back to results</button></div>`:`<div class="panel"><span class="pill locked">Full edition</span><h3>Unlock this prompt with your purchase.</h3><p>The full edition includes this prompt and its guidance. Activate with the license key from your Gumroad receipt.</p><div class="actions"><a class="button primary" href="/access">Activate or recover access</a><a class="button" href="/library?sample=1">Try the free samples</a></div></div>`);
if(!dialog.open)dialog.showModal();dialog.scrollTop=0;$('dialog-title').focus();}
$('close-dialog')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>{document.body.append($('toast'));$('toast').textContent='';if(location.hash.startsWith('#prompt-'))history.replaceState(null,'',location.pathname+location.search);});
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied. Paste it into your AI tool.');}catch{toast('Clipboard access is unavailable. Select the prompt text and copy it manually.');}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close-prompt'))dialog?.close();if(b.dataset.open){history.replaceState(null,'',location.pathname+location.search+'#prompt-'+b.dataset.open);openPrompt(Number(b.dataset.open));}if(b.dataset.favorite){toggle('favorites',Number(b.dataset.favorite));renderLibrary();renderToolkit();document.querySelector(`[data-favorite="${b.dataset.favorite}"]`)?.focus();if(b.isConnected){b.setAttribute('aria-pressed',String(state.favorites.includes(Number(b.dataset.favorite))));b.textContent=state.favorites.includes(Number(b.dataset.favorite))?'Saved':'Save';}}if(b.dataset.copy){const p=available(Number(b.dataset.copy));if(p)copy(p.prompt);}if(b.dataset.complete){toggle('completed',Number(b.dataset.complete));b.setAttribute('aria-pressed',String(state.completed.includes(Number(b.dataset.complete))));b.textContent=state.completed.includes(Number(b.dataset.complete))?'Reviewed':'Mark reviewed';}});
const hashPrompt=()=>{const match=location.hash.match(/^#prompt-(\d+)$/);if(match)openPrompt(Number(match[1]));};hashPrompt();window.addEventListener('hashchange',hashPrompt);
function locked(title){return `<section class="panel"><span class="pill locked">Full edition</span><h2>${escape(title)}</h2><p>Included in the complete playbook.</p><a class="button" href="/access">Edition access</a></section>`;}
function workflow(w){const done=w.steps.filter(id=>state.steps.includes(`${w.id}-${id}`)).length;return `<section class="panel"><div class="workflow-meta"><h2>${escape(w.title)}</h2><span class="quiet">${done}/${w.steps.length} steps</span></div><progress max="${w.steps.length}" value="${done}" aria-label="${escape(w.title)} progress"></progress>${w.steps.map(id=>`<label class="check-item"><input type="checkbox" data-step="${w.id}-${id}" ${state.steps.includes(`${w.id}-${id}`)?'checked':''}/><span>${escape(catalog.prompts.find(p=>p.id===id).title)}</span><a href="/library#prompt-${id}">${available(id)?'Read prompt':'View topic'}</a></label>`).join('')}<p class="quiet" style="margin-top:20px">${escape(w.stop)}</p>${!unlocked?'<p class="quiet">This sample workflow shows the full sequence. Some steps refer to full-edition prompts.</p>':''}</section>`;}
function renderWorkflows(){if($('workflow-list'))$('workflow-list').innerHTML=catalog.workflows.map(meta=>{const w=edition.workflows.find(w=>w.id===meta.id);return w?workflow(w):locked(meta.title);}).join('');}
function renderChecks(){if(!$('checklist-list'))return;let total=0,done=0;$('checklist-list').innerHTML=catalog.checklists.map(meta=>{const c=edition.checklists.find(c=>c.id===meta.id);if(!c)return locked(meta.title);total+=c.items.length;done+=c.items.filter((_,i)=>state.checks.includes(`${c.id}-${i}`)).length;return `<section class="panel"><h2>${escape(c.title)}</h2>${c.items.map((item,i)=>`<label class="check-item"><input type="checkbox" data-check="${c.id}-${i}" ${state.checks.includes(`${c.id}-${i}`)?'checked':''}/><span>${escape(item)}</span></label>`).join('')}</section>`;}).join('');$('check-progress').textContent=`${done} of ${total} available review items checked`;}
renderWorkflows();renderChecks();
document.addEventListener('change',e=>{if(e.target.dataset.check){toggle('checks',e.target.dataset.check);const total=edition.checklists.reduce((n,c)=>n+c.items.length,0);const done=edition.checklists.reduce((n,c)=>n+c.items.filter((_,i)=>state.checks.includes(`${c.id}-${i}`)).length,0);$('check-progress').textContent=`${done} of ${total} available review items checked`;}if(e.target.dataset.step){toggle('steps',e.target.dataset.step);const panel=e.target.closest('.panel');const boxes=[...panel.querySelectorAll('[data-step]')];const done=boxes.filter(b=>b.checked).length;panel.querySelector('progress').value=done;panel.querySelector('.workflow-meta .quiet').textContent=`${done}/${boxes.length} steps`;}});
if($('lesson-list'))$('lesson-list').innerHTML=catalog.lessons.map(meta=>{const l=edition.lessons.find(l=>l.id===meta.id);return l?`<details class="panel"><summary>${escape(l.title)}</summary><div class="lesson-body">${escape(l.body)}</div></details>`:locked(meta.title);}).join('');
const fixes=[['I don’t know what looks wrong',1,'Start with an audit. Fix the top three usability issues before changing the visual style.'],['The phone version feels cramped',2,'Check layout, keyboard behavior, overflow, and touch targets in that order.'],['There are too many buttons and screens',3,'Map the important tasks, then simplify where they live. Preserve useful features.'],['It looks obviously AI-generated',4,'Remove unnecessary decoration and repetitive explanations. Keep the product’s identity.'],['I’m about to launch a feature',5,'Review the real flow, including loading, errors, accessibility, and regression risks.'],['I keep redesigning the same screen',6,'Compare against the original goal and separate usability issues from preferences.'],['I’m adding collaboration',7,'Review invitations, presence, shared activity, and roles before final QA.'],['I’m adding a paid upgrade',8,'Make the offer, costs, access, and billing controls clear before launch.']];
if($('fix-list')){$('fix-list').innerHTML=fixes.map(([title,id,description])=>`<button class="panel fix-choice" data-fix="${id}"><span class="tiny">START HERE · ${String(id).padStart(2,'0')}</span><h3 style="margin-top:16px">${escape(title)}</h3><p>${escape(description)}</p></button>`).join('');$('fix-list').addEventListener('click',e=>{const b=e.target.closest('[data-fix]');if(!b)return;const id=Number(b.dataset.fix),w=edition.workflows.find(w=>w.id===id);$('fix-result').hidden=false;$('fix-result').innerHTML=w?workflow(w):`<h2>${escape(fixes[id-1][0])}</h2><p>${escape(fixes[id-1][2])}</p><p>The complete step-by-step workflow is in the full edition. You can start with the free full UI audit.</p><a class="button primary" href="/library#prompt-1">Open the free audit</a><a class="button" href="/access">Edition access</a>`;$('fix-result').focus();$('fix-result').scrollIntoView({block:'start',behavior:'auto'});});}
function generate(){const form=$('builder-form');if(!form)return;const values=Object.fromEntries(new FormData(form));state.brief=values;save();const p=available(Number(values.template));if(!p)return;let text=p.prompt;for(const name of ['app','screen','audience','goal','issue','constraints'])values[name]=String(values[name]||'').trim();if(['app','screen','audience','goal'].some(name=>!values[name])){toast('Add a project, screen, audience, and goal before building.');return false;}const replacements={'[APP NAME]':values.app,'[SCREEN / FEATURE]':values.screen,'[TARGET USER]':values.audience,'[WHAT THE USER SHOULD ACCOMPLISH]':values.goal,"[DESCRIBE IT, OR WRITE 'UNKNOWN']":values.issue||'UNKNOWN'};for(const [from,to] of Object.entries(replacements))text=text.split(from).join(to||from);if(values.mode==='implement')text+='\n\nAfter diagnosing the named issue, implement the smallest targeted fix. Preserve working functionality and user data. List the files changed and tests run. Separate verified results from manual checks still needed.';else text+='\n\nThis is a diagnosis only. Do not edit code yet.';if(values.constraints.trim())text+='\n\nAdditional constraints:\n'+values.constraints.trim();$('built-prompt').value=text;$('copy-built').disabled=false;$('builder-status').textContent='Ready. Copy this prompt and paste it into your AI tool.';$('built-prompt').closest('section').querySelector('h2').textContent='Your prompt is ready.';}
if($('builder-form')){edition.prompts.forEach(p=>$('template').add(new Option(`${String(p.id).padStart(2,'0')} · ${p.title}`,String(p.id))));const form=$('builder-form');for(const [key,value] of Object.entries(state.brief)){const field=form.elements.namedItem(key);if(field&&key!=='template')field.value=value;}const desired=new URLSearchParams(location.search).get('prompt')||state.brief.template;if(desired&&available(Number(desired)))$('template').value=desired;else if(desired)toast('That prompt needs the full edition. The free audit is selected.');form.addEventListener('submit',e=>{e.preventDefault();generate();});form.addEventListener('input',()=>{state.brief=Object.fromEntries(new FormData(form));save();$('built-prompt').value='';$('copy-built').disabled=true;$('builder-status').textContent='Your details changed. Select Build my prompt to update the result.';$('built-prompt').closest('section').querySelector('h2').textContent='Build your updated prompt.';});$('copy-built').addEventListener('click',()=>copy($('built-prompt').value));}
function renderToolkit(){if(!$('toolkit-stats'))return;$('toolkit-stats').innerHTML=`<div><strong>${state.favorites.length}</strong><span>Saved prompts</span></div><div><strong>${state.completed.length}</strong><span>Prompts reviewed</span></div><div><strong>${state.checks.length}</strong><span>Checklist items reviewed</span></div>`;$('favorites-list').innerHTML=catalog.prompts.filter(p=>state.favorites.includes(p.id)).map(row).join('')||'<p class="empty">No saved prompts yet. <a href="/library">Explore the library</a> and save one for your next project.</p>';}
renderToolkit();
if($('notes')){$('notes').value=state.notes;$('notes').addEventListener('input',()=>{state.notes=$('notes').value;$('notes-status').textContent=save()?'Saved on this device.':'Could not save. Export a backup before leaving.';});$('export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='UI-Prompt-Package-Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('backup-status').textContent='Backup download requested.';});$('import').addEventListener('change',async()=>{try{const file=$('import').files[0];if(!file)return;if(file.size>150000)throw Error('Choose a backup smaller than 150 KB.');const incoming=validate(JSON.parse(await file.text()));const notes=incoming.notes&&incoming.notes!==state.notes?[state.notes,incoming.notes].filter(Boolean).join('\n\n— Imported notes —\n\n'):state.notes;if(notes.length>20000)throw Error('The combined notes exceed 20,000 characters. Shorten them before importing.');const merged={...state,notes};for(const k of ['favorites','completed','checks','steps'])merged[k]=unique([...state[k],...incoming[k]]);if(!Object.values(state.brief).some(Boolean))merged.brief=incoming.brief;state=validate(merged);const saved=save();$('notes').value=state.notes;renderToolkit();$('backup-status').textContent=saved?'Backup merged. Existing saved items were kept.':'Backup merged in memory. Export it now because browser storage is unavailable.';}catch(error){$('backup-status').textContent=error.message||'That backup could not be read.';}finally{$('import').value='';}});}
$('unlock-form')?.addEventListener('submit',async e=>{
 e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;$('unlock-status').textContent='Checking your purchase…';
 try{
  const license=$('access-key').value.trim();
  await accessRequest('/api/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({license})});
  $('access-key').value='';
  await accessRequest('/api/edition'); // Confirm the browser actually accepted the secure cookie.
  accessChannel?.postMessage('activated');location.assign('/library');
 }catch(error){$('unlock-status').textContent=error.name==='TimeoutError'?'The check took too long. Please try again; you won’t be charged again.':error.message;}
 finally{b.disabled=false;}
});
// Enable only after the secure JSON submission handler has been installed.
if($('unlock-form'))$('unlock-form').querySelector('button[type="submit"]').disabled=false;
$('lock-edition')?.addEventListener('click',async()=>{
 try{await accessRequest('/api/logout',{method:'POST'});accessChannel?.postMessage('logout');location.reload();}
 catch{$('unlock-status').textContent='We couldn’t sign you out. Please try again.';}
});
