import { test } from 'node:test';
import assert from 'node:assert/strict';
import { passwordHash, adminConfig, ADMIN_COOKIE, digest, SESSION_SECONDS } from '../server/admin-auth.mjs';
import { makeAdminHandler } from '../server/admin-handler.mjs';
import { makeSubmissionHandler } from '../server/submissions.mjs';
import { makePublicHandler } from '../server/public-community.mjs';
import { validateEdit, saveRecord } from '../server/admin-store.mjs';
import { testRedis } from './helpers/redis.mjs';
const origin='https://owner.test';
test('admin configuration fails closed and packet editing is forbidden',()=>{
 assert.throws(()=>adminConfig({}),e=>e.status===503);
 assert.throws(()=>validateEdit('product',{id:'ui-ux-prompt-packet',revision:0},null),e=>e.status===400);
 for(const host of ['digitalpromptpackage.vercel.app','digivated.vercel.app'])assert.throws(()=>validateEdit('product',{id:'copy-packet',revision:0,status:'published',description:'Test',name:'Test',url:`https://${host}/ui-ux-prompt-packet`},null),e=>e.status===400);
 assert.throws(()=>validateEdit('product',{id:'other-product',revision:0,status:'published',description:'Test',name:'Test',url:'javascript:alert(1)'},null),e=>e.status===400);
});
test('real Redis: owner security, atomic moderation, publishing, withdrawal and images',{skip:!process.env.DIGIVATED_TEST_REDIS_PORT},async()=>{
 const redis=testRedis(14);await redis(['FLUSHDB']);
 const password='Test-only owner password 2026!';const env={DIGIVATED_ADMIN_PASSWORD_HASH:await passwordHash(password),DIGIVATED_ADMIN_SESSION_SECRET:'a'.repeat(64),DIGIVATED_ADMIN_ORIGIN:origin};
 const handler=makeAdminHandler({env,redis});let cookie='',csrf='';
 const invoke=async(fn,{method='GET',url='/api/admin',body,headers={}}={})=>{let result;const out={};const req={method,url,body,headers:{origin,'content-type':'application/json','x-real-ip':'fixture',cookie,'x-admin-csrf':csrf,...headers}};const res={statusCode:200,setHeader:(k,v)=>out[k]=v,end:b=>{result=Buffer.isBuffer(b)?b:JSON.parse(b);}};await fn(req,res);return {status:res.statusCode,body:result,headers:out};};
 assert.equal((await invoke(handler,{url:'/api/admin?action=list&kind=submission'})).status,401);
 assert.equal((await invoke(handler,{method:'POST',body:{action:'login',password},headers:{origin:'https://evil.test'}})).status,403);
 assert.equal((await invoke(handler,{method:'POST',body:{action:'login',password:'wrong'}})).status,401);
 const login=await invoke(handler,{method:'POST',body:{action:'login',password}});assert.equal(login.status,200);assert.match(login.headers['Set-Cookie'],/HttpOnly; Secure; SameSite=Strict/);assert.ok(login.headers['Set-Cookie'].startsWith(ADMIN_COOKIE+'='));cookie=login.headers['Set-Cookie'].split(';')[0];csrf=login.body.csrf;
 assert.equal((await invoke(handler)).status,200);
 const sessionKey=`digivated:admin:session:${digest(cookie.split('=')[1])}`;
 const ttl=await redis(['TTL',sessionKey]);assert.ok(ttl>0&&ttl<=SESSION_SECONDS);
 assert.equal((await invoke(handler,{headers:{cookie:`${ADMIN_COOKIE}=${'f'.repeat(64)}`}})).status,401);
 const storedSession=await redis(['GET',sessionKey]);await redis(['EXPIRE',sessionKey,0]);assert.equal((await invoke(handler)).status,401);await redis(['SET',sessionKey,storedSession,'EX',SESSION_SECONDS]);
 assert.equal((await invoke(handler,{method:'POST',body:{action:'logout'},headers:{'x-admin-csrf':'wrong'}})).status,403);
 const submission=makeSubmissionHandler({env:{SUBMISSIONS_ORIGIN:origin},redis});const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aFJkAAAAASUVORK5CYII=';
 const input={creator:'Fixture creator',email:'private@example.com',name:'Fixture build',url:'https://example.com',description:'A fixture project for testing owner moderation.',category:'Apps',notes:'PRIVATE NOTES',image:png,consent:true};
 const submitted=await invoke(submission,{method:'POST',body:input,url:'/api/submissions'});assert.equal(submitted.status,201);const id=submitted.body.id;
 const projects=makePublicHandler('projects',{redis});assert.equal((await invoke(projects,{url:'/api/projects'})).body.items.length,0);assert.equal((await invoke(projects,{url:`/api/projects?image=${id}`})).status,404);
 const detail=await invoke(handler,{url:`/api/admin?action=detail&kind=submission&id=${id}`});const pending=detail.body.record;
 assert.equal((await invoke(handler,{method:'POST',body:{action:'save',kind:'submission',record:{...pending,revision:0,status:'featured'}}})).status,400);
 const approved=await invoke(handler,{method:'POST',body:{action:'save',kind:'submission',record:{...pending,revision:0,status:'approved',pick:true}}});assert.equal(approved.status,200);
 const published=await invoke(projects,{url:'/api/projects'});assert.equal(published.body.items.length,1);const serial=JSON.stringify(published.body);assert.ok(!serial.includes('private@example.com'));assert.ok(!serial.includes('PRIVATE NOTES'));assert.ok(!serial.includes('consent'));assert.equal((await invoke(projects,{url:`/api/projects?image=${id}`})).status,200);
 const competing=await Promise.allSettled([saveRecord(redis,'submission',{...approved.body.record,status:'featured'}),saveRecord(redis,'submission',{...approved.body.record,status:'archived'})]);assert.equal(competing.filter(r=>r.status==='rejected'&&r.reason.status===409).length,1);
 let after=JSON.parse(await redis(['GET',`digivated:submission:${id}`]));
 if(after.status!=='featured'){after=await saveRecord(redis,'submission',{...after,status:'approved'});await saveRecord(redis,'submission',{...after,status:'featured'});}
 const submitted2=await invoke(submission,{method:'POST',body:{...input,name:'Second fixture'},url:'/api/submissions'});const id2=submitted2.body.id;const pending2=JSON.parse(await redis(['GET',`digivated:submission:${id2}`]));
 const approved2=await saveRecord(redis,'submission',{...pending2,revision:0,status:'approved'});await saveRecord(redis,'submission',{...approved2,status:'featured'});
 assert.equal(await redis(['GET','digivated:featured']),id2);
 const previous=JSON.parse(await redis(['GET',`digivated:submission:${id}`]));assert.notEqual(previous.status,'featured');
 await saveRecord(redis,'submission',{...previous,status:'archived'});assert.equal((await invoke(projects,{url:`/api/projects?image=${id}`})).status,404);
 const resource={id:'test-article',revision:0,status:'draft',title:'Fixture article',description:'A fixture summary',category:'Tech',publishedDate:'2026-10-05',readingTime:3,content:'## A section\n\nEscaped <script> text.',related:'',image:png};
 let article=await saveRecord(redis,'resource',resource);const content=makePublicHandler('content',{redis});assert.equal((await invoke(content,{url:'/api/content?type=resource&id=test-article'})).status,404);
 article=await saveRecord(redis,'resource',{...article,related:'',status:'published'});assert.equal((await invoke(content,{url:'/api/content?type=resource&id=test-article'})).body.item.content,resource.content);assert.equal((await invoke(content,{url:'/api/content?type=resource'})).body.items[0].content,undefined);
 await saveRecord(redis,'resource',{...article,related:'',status:'archived'});assert.equal((await invoke(content,{url:'/api/content?type=resource&id=test-article'})).status,404);
 assert.equal((await invoke(handler,{method:'POST',body:{action:'save',kind:'product',record:{id:'ui-ux-prompt-packet',revision:0}}})).status,400);
 const product=await saveRecord(redis,'product',{id:'test-product',revision:0,status:'published',name:'Fixture product',description:'Fixture description',url:'https://example.com/product'});assert.equal((await invoke(content,{url:'/api/content?type=product'})).body.items[0].name,product.name);
 const rotated=makeAdminHandler({env:{...env,DIGIVATED_ADMIN_SESSION_SECRET:'b'.repeat(64)},redis});assert.equal((await invoke(rotated)).status,401);
 assert.equal((await invoke(handler,{method:'POST',body:{action:'logout'}})).status,200);assert.equal((await invoke(handler)).status,401);
 for(let i=0;i<4;i++)await invoke(handler,{method:'POST',body:{action:'login',password:'wrong'}});
 assert.equal((await invoke(handler,{method:'POST',body:{action:'login',password}})).status,429);
 await redis(['FLUSHDB']);
});
